# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e720732ed268721f8055894232e841fe8266b7c68fb7120fb27b0066a931d294bd89cd698f5bbd5fcdf0088fb5e10ceffda68aa23a64cd678844640a4f452b84

test:
  secret_key_base: abd7e0979406302c701409cd90d4380b33723be9273bea64fb0edd029acd2efcbe3a12e316dd1f9e7aff595c6991d2825ce6234f318353833a145361bf93954f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
